# Generated by Django 5.2.1 on 2025-06-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_customuser_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
