# Generated by Django 5.2.1 on 2025-06-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
