# Generated by Django 5.2.1 on 2025-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
